kind: pipeline
type: docker
name: default

steps:
    - name: build
      image: docker
      volumes:
          - name: socket
            path: /var/run/docker.sock
      commands:
          - docker build -t automation .

    - name: deploy
      image: docker
      volumes:
          - name: socket
            path: /var/run/docker.sock
      environment:
          MQTT_PASSWORD:
              from_secret: MQTT_PASSWORD
          HUE_TOKEN:
              from_secret: HUE_TOKEN
          NTFY_TOPIC:
              from_secret: NTFY_TOPIC
          GOOGLE_OAUTH_URL:
              from_secret: GOOGLE_OAUTH_URL
          GOOGLE_CREDENTIALS:
              from_secret: GOOGLE_CREDENTIALS
      commands:
          - docker stop automation || true

          - docker rm automation || true

          - docker create -e MQTT_PASSWORD=$MQTT_PASSWORD -e HUE_TOKEN=$HUE_TOKEN -e NTFY_TOPIC=$NTFY_TOPIC -e GOOGLE_OAUTH_URL=$GOOGLE_OAUTH_URL -e GOOGLE_CREDENTIALS=$GOOGLE_CREDENTIALS --network mqtt --name automation automation
          - docker network connect mqtt automation
          - docker network connect web automation
          - docker start automation

      when:
        branch:
          - master
        event:
          exclude:
            - pull_request

volumes:
    - name: socket
      host:
          path: /var/run/docker.sock
