hue:
  ip: 10.0.0.146

mqtt:
  host: mosquitto
  port: 8883
  username: mqtt
  client_id: automation

zigbee:
  prefix: zigbee2mqtt

kasa:
  outlets:
    living_room/mixer: 10.0.0.49
    living_room/speakers: 10.0.0.182

computers:
  living_room/zeus:
    mac: 30:9c:23:60:9c:13
    room: Living Room
    url: http://10.0.0.2:9000/start-pc?mac=30:9c:23:60:9c:13

google:
  username: Dreaded_X
